### ISSUE TITLE
build.sh wipes home directory

### ISSUE THREAD

**Issue by dzruyk** [boolivar/pijoy#3]
If user does not set KERNEL_DIR variable build.sh wipes all files from $HOME and that's hurts a lot :'-(

You can put KERNEL_DIR in double quotes, like that
```
cd "${KERNEL_DIR}" && rm -rf ./*
```
or (more secure) check is variable defined before `rm -rf`

**Comment by boolivar** [comment]
I'm really sorry for that 😰 This script provided as part of docker image so I didn't expect such a problem to happen. Anyways, I would appreciate any PRs to resolve existing issues.
